title: car
type: object
properties:
  make:
    type: string
  model:
    type: string
  trim:
    type: string
  year:
    type: year
  purchaseDate:
    type: string
    format: ISO8601
  purchaseMiles:
    type: number
  rules:
    type: array
    items: 
      title: rule
      type: object
      properties: 
        item:
          type: string
        verb:
          type: string
        phase:
          type: string
          enum: [initial, ongoing]
          description: >
            Lifecycle phase for rules that have different intervals at different
            stages of the vehicle's life. Used to disambiguate rules with the
            same item/verb combination. Optional for rules that apply throughout.
        intervalMiles:
          type: number
        intervalMonths:
          type: number
        severeIntervalMiles:
          type: number
        severeIntervalMonths:
          type: number
        notes:
          type: string
        startMiles:
          type: number
          default: 0
        stopMiles:
          type: number
          default: 999999999
        startMonths:
          type: number
          default: 0
        stopMonths:
          type: number
          default: 9999
        aftermarket:
          type: boolean
          default: false
      required:
        - item
        - verb
        # At least one of intervalMiles or intervalMonths should be provided
required:
  - make
  - model
  - trim
  - year
  - purchaseDate
  - purchaseMiles
  - rules